apiVersion: operator.openshift.io/v1
kind: KubeControllerManager
metadata:
  name: cluster
spec:
  extendedArguments:
    node-monitor-grace-period:
    - "30s"
    pod-eviction-timeout:
    - "120s"
    node-monitor-period:
    - "5s"