apiVersion: self-node-remediation.medik8s.io/v1alpha1
kind: SelfNodeRemediationTemplate
metadata:
  name: self-node-remediation-resource-deletion-template
  namespace: openshift-workload-availability
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  template:
    spec:
      remediationStrategy: ResourceDeletion