apiVersion: self-node-remediation.medik8s.io/v1alpha1
kind: SelfNodeRemediationTemplate
metadata:
  name: self-node-remediation-template
  namespace: openshift-workload-availability
  labels:
    nimmo: test
spec:
  template:
    spec:
      remediationStrategy: Automatic