apiVersion: machineconfiguration.openshift.io/v1
kind: KubeletConfig
metadata:
  name: fast-fail-kubeletconfig
spec:
  machineConfigPoolSelector:
    matchLabels:
      pools.operator.machineconfiguration.openshift.io/worker: ""
  kubeletConfig:
    # 1. How often the kubelet reports its status (default: 10s)
    # A faster report rate aids faster detection.
    nodeStatusUpdateFrequency: "5s" 
    
    # 2. How long pods on the node tolerate the "NotReady" or "Unreachable" 
    # taints before eviction begins (default: 300s / 5m)
    # Reducing this speeds up pod rescheduling.
    defaultNotReadyTolerationSeconds: 60
    defaultUnreachableTolerationSeconds: 60