apiVersion: machineconfiguration.openshift.io/v1
kind: KubeletConfig
metadata:
  name: worker-node-timing
spec:
  machineConfigPoolSelector:
    matchLabels:
      # MUST CHANGE THIS ON non-3-node clusters
      pools.operator.machineconfiguration.openshift.io/master: ""
  kubeletConfig:
    nodeStatusUpdateFrequency: 4s
    nodeStatusReportFrequency: 30s