apiVersion: imageregistry.operator.openshift.io/v1
kind: Config
metadata:
  name: cluster
spec:
  managementState: Managed
  replicas: 3
  storage:
    pvc:
      claim: openshift-image-registry-storage