apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openshift-image-registry-storage
  namespace: openshift-image-registry
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: ocs-storagecluster-cephfs