apiVersion: operator.openshift.io/v1
kind: KubeDescheduler
metadata:
  name: cluster-basic
  namespace: openshift-kube-descheduler-operator
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  deschedulingIntervalSeconds: 3600
  logLevel: Normal
  managementState: Managed
  mode: Automatic
  observedConfig:
    servingInfo:
      cipherSuites:
        - TLS_AES_128_GCM_SHA256
        - TLS_AES_256_GCM_SHA384
        - TLS_CHACHA20_POLY1305_SHA256
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
      minTLSVersion: VersionTLS12
  operatorLogLevel: Normal
  profiles:
    - DevKubeVirtRelieveAndMigrate
  unsupportedConfigOverrides: null