apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: openshift-storage
resources:
  - namespace.yaml
  - operator-group.yaml
  - local-storage-subscription.yaml
  - odf-operator-subscription.yaml
  - auto-discover-devices.yaml