apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-patches
  namespace: openshift-gitops-cluster
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: cluster
  source:
    kustomize:
      patches:
        - target:
            group: config.openshift.io
            version: v1
            kind: OAuth
            name: cluster
          patch: |-
            - op: add
              path: /spec/tokenConfig/accessTokenMaxAgeSeconds
              value: 86401
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true